import streamlit as st
import numpy as np
import cv2
import pandas as pd

from src.catalog import load_catalog
from src.camera import Camera
from src.simulator import render_starfield, NoiseParams
from src.identifier import StarIdentifier
from src import pipeline

CATALOG_PATH = "data/catalog/hygdata_v42_compact.csv"
IMG_WIDTH    = 1280
IMG_HEIGHT   = 720
FOV_DEG      = 60.0
MAG_LIMIT    = 8.0
ID_MAG_LIMIT = 5.5

st.set_page_config(page_title="Spacecraft Attitude Finder", layout="wide")
st.title("Spacecraft Attitude Finder")


@st.cache_resource
def load_resources():
    catalog = load_catalog(CATALOG_PATH, mag_limit=MAG_LIMIT)
    identifier = StarIdentifier(
        catalog=catalog,
        fov_deg=FOV_DEG,
        img_width=IMG_WIDTH,
        img_height=IMG_HEIGHT,
        mag_limit=ID_MAG_LIMIT,
        angle_tol_deg=0.4,
    )
    return catalog, identifier


def annotate_image(img_gray: np.ndarray, result) -> np.ndarray:
    vis = cv2.cvtColor(img_gray, cv2.COLOR_GRAY2BGR)
    matched_c_ids = {c_idx for c_idx, _ in result.matches}
    for i, (cx, cy, _) in enumerate(result.centroids):
        color = (50, 220, 50) if i in matched_c_ids else (60, 60, 200)
        cv2.circle(vis, (int(cx), int(cy)), 10, color, 1, lineType=cv2.LINE_AA)
    return vis


def get_star_rows(result, identifier) -> list:
    rows = []
    for _, b_idx in result.matches:
        row = identifier.bright_catalog.iloc[b_idx]
        proper = str(row["proper"])
        hip    = row["hip"]
        if proper and proper != "nan":
            name = proper
        elif str(hip) not in ("nan", ""):
            name = f"HIP {int(float(hip))}"
        else:
            name = "—"
        rows.append({
            "Star": name,
            "Mag": round(float(row["mag"]), 2),
            "RA (°)": round(float(row["ra_deg"]), 4),
            "Dec (°)": round(float(row["dec_deg"]), 4),
        })
    rows.sort(key=lambda r: r["Mag"])
    return rows


with st.spinner("Loading catalog and building star index..."):
    catalog, identifier = load_resources()

left, right = st.columns([1, 1.6])

# LEFT COLUMN
with left:
    mode = st.radio("Mode", ["Generate Synthetic Image", "Upload Image"], horizontal=True)
    st.divider()

    # GENERATE MODE
    if mode == "Generate Synthetic Image":
        if st.button("Randomize Pointing", use_container_width=True):
            xyz = catalog[["x", "y", "z"]].values
            idx = np.random.randint(0, len(xyz))
            vx, vy, vz = map(float, xyz[idx])
            st.session_state["ra"]  = float((np.degrees(np.arctan2(vy, vx)) + 360.0) % 360.0)
            st.session_state["dec"] = float(np.degrees(np.arcsin(np.clip(vz, -1.0, 1.0))))

        ra  = st.number_input("RA (°)",   0.0,  360.0, float(st.session_state.get("ra",  180.0)), step=0.5)
        dec = st.number_input("Dec (°)", -90.0,  90.0, float(st.session_state.get("dec",   0.0)), step=0.5)

        with st.expander("Noise settings"):
            g_sigma  = st.slider("Gaussian sigma",   0.0, 10.0, 5.0,    0.5)
            vignette = st.slider("Vignette",          0.0,  1.0, 0.3,    0.05)
            bloom    = st.slider("Bloom intensity",   0.0,  1.0, 0.3,    0.05)
            hot_px   = st.slider("Hot pixel prob",    0.0,  0.005, 0.0001, 0.0001, format="%.4f")
            cosmic   = st.slider("Cosmic ray prob",   0.0,  0.005, 0.0005, 0.0001, format="%.4f")

        if st.button("Generate & Solve", type="primary", use_container_width=True):
            cam = Camera(width=IMG_WIDTH, height=IMG_HEIGHT, fov_deg=FOV_DEG)
            cam.point_at(ra_deg=ra, dec_deg=dec)
            noise = NoiseParams(
                gaussian_sigma=g_sigma,
                hot_pixel_prob=hot_px,
                cosmic_ray_prob=cosmic,
                vignette_strength=vignette,
                bloom_threshold=0.8,
                bloom_intensity=bloom,
                twinkle_amount=0.2,
            )
            with st.spinner("Rendering starfield..."):
                img = render_starfield(cam, catalog, noise)
            with st.spinner("Solving attitude..."):
                result = pipeline.solve(img, identifier, cam.focal, IMG_WIDTH, IMG_HEIGHT)
            st.session_state["gen_img"]    = img
            st.session_state["gen_result"] = result

        if "gen_img" in st.session_state:
            st.image(st.session_state["gen_img"], caption="Synthetic image", use_container_width=True)

    # UPLOAD MODE
    else:
        st.caption("Best results with 1280×720 images generated by this app.")
        uploaded = st.file_uploader("Upload a star image", type=["png", "jpg", "jpeg"])
        if uploaded:
            file_bytes = np.frombuffer(uploaded.read(), np.uint8)
            img = cv2.imdecode(file_bytes, cv2.IMREAD_GRAYSCALE)
            if img is None:
                st.error("Could not decode image.")
            else:
                h, w = img.shape
                focal = (w / 2.0) / np.tan(np.deg2rad(FOV_DEG / 2.0))
                with st.spinner("Solving attitude..."):
                    result = pipeline.solve(img, identifier, focal, w, h)
                st.session_state["up_img"]    = img
                st.session_state["up_result"] = result

        if "up_img" in st.session_state:
            st.image(st.session_state["up_img"], caption="Uploaded image", use_container_width=True)


# RIGHT COLUMN
with right:
    img_key    = "gen_img"    if mode == "Generate Synthetic Image" else "up_img"
    result_key = "gen_result" if mode == "Generate Synthetic Image" else "up_result"

    if img_key in st.session_state and result_key in st.session_state:
        img    = st.session_state[img_key]
        result = st.session_state[result_key]

        annotated = annotate_image(img, result)
        legend = "🟢 Matched stars 🔵 Detected stars"
        st.image(annotated, caption=f"Identified stars — {legend}", use_container_width=True)

        st.divider()

        if result.success:
            st.subheader("Attitude of Spacecraft")
            c1, c2, c3, c4 = st.columns(4)
            c1.metric("RA",       f"{result.ra_deg:.3f}°")
            c2.metric("Dec",      f"{result.dec_deg:.3f}°")
            c3.metric("Roll",     f"{result.roll_deg:.3f}°")
            c4.metric("Residual", f"{result.residual_deg:.4f}°")
            st.caption(f"{result.n_matches} matched / {result.n_centroids} detected")

            star_rows = get_star_rows(result, identifier)
            if star_rows:
                st.subheader("Identified Stars")
                st.dataframe(pd.DataFrame(star_rows), use_container_width=True, hide_index=True)
        else:
            st.warning(
                f"Attitude solve failed — {result.n_centroids} centroids detected, "
                f"{result.n_matches} matched. Try a different pointing."
            )
    else:
        st.info("← Generate or upload an image to see results here.")
